name: Publish to FTP

on:
  # Triggers on both manual run and when gh-pages is updated
  workflow_dispatch:
  page_build:
  # Also catch direct pushes to gh-pages if they happen
  push:
    branches:
      - gh-pages

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/  # Adjust this path as needed
          local-dir: ./             # This will upload everything from gh-pages branch
